import flask
from application import db


class FaASCE710(db.Document):
    _id         =   db.ObjectIdField()
    SiteClass   =   db.StringField( max_length=10 )
    ss25        =   db.FloatField( )
    ss50        =   db.FloatField( )
    ss75        =   db.FloatField( )
    ss100       =   db.FloatField( )
    ss125       =   db.FloatField( )

    meta = {'db_alias': 'calc_db', 'collection': 'FaASCE710'}


class FaASCE716(db.Document):
    _id         =   db.ObjectIdField()
    SiteClass   =   db.StringField( max_length=10 )
    ss25        =   db.FloatField( )
    ss50        =   db.FloatField( )
    ss75        =   db.FloatField( )
    ss100       =   db.FloatField( )
    ss125       =   db.FloatField( )

    meta = {'db_alias': 'calc_db', 'collection': 'FaASCE716'}

class FvASCE716(db.Document):
    _id         =   db.ObjectIdField()
    SiteClass   =   db.StringField( max_length=10 )
    s11        =   db.FloatField( )
    s12        =   db.FloatField( )
    s13        =   db.FloatField( )
    s14       =   db.FloatField( )
    s15       =   db.FloatField( )
    s16       =   db.FloatField( )

    meta = {'db_alias': 'calc_db', 'collection': 'FvASCE716'}


class AISCSectionsRectangular(db.Document):
    _id         =   db.ObjectIdField()
    Type        =   db.StringField()
    EDI_Std_Nomenclature  = db.StringField()
    AISC_name   =   db.StringField()
    T_F         =   db.StringField()
    W           =   db.FloatField( )
    A           =   db.FloatField( )
    Ht            =   db.FloatField( )
    h           =   db.FloatField( )
    B           =   db.FloatField( )
    b           =   db.FloatField( )
    tnom            =   db.FloatField( )
    tdes            =   db.FloatField( )
    Ix            =   db.FloatField( )
    Zx            =   db.FloatField( )
    Sx            =   db.FloatField( )
    rx            =   db.FloatField( )
    Iy            =   db.FloatField( )
    Zy            =   db.FloatField( )
    Sy            =   db.FloatField( )
    ry            =   db.FloatField( )
    J            =   db.FloatField( )
    C            =   db.FloatField( )
    bltdes            =   db.FloatField( )
    hltdes            =   db.FloatField( )

    meta = {'db_alias': 'calc_db', 'collection': 'aisc_sections_rectangular'}

class AISCSectionsCircular(db.Document):
    _id         =   db.ObjectIdField()
    Type        =   db.StringField()
    EDI_Std_Nomenclature  = db.StringField()
    AISC_name   =   db.StringField()
    T_F         =   db.StringField()
    W           =   db.FloatField( )
    A           =   db.FloatField( )
    OD            =   db.FloatField( )
    tnom           =   db.FloatField( )
    tdes           =   db.FloatField( )
    Ix            =   db.FloatField( )
    Zx            =   db.FloatField( )
    Sx            =   db.FloatField( )
    rx            =   db.FloatField( )
    Iy            =   db.FloatField( )
    Zy            =   db.FloatField( )
    Sy            =   db.FloatField( )
    ry            =   db.FloatField( )
    J            =   db.FloatField( )
    C            =   db.FloatField( )
    Dlt            =   db.FloatField( )

    meta = {'db_alias': 'calc_db', 'collection': 'aisc_sections_circular'}

class AISCSectionsChannel(db.Document):
    _id         =   db.ObjectIdField()
    Type        =   db.StringField()
    EDI_Std_Nomenclature  = db.StringField()
    AISC_name   =   db.StringField()
    T_F         =   db.StringField()
    W           =   db.FloatField( )
    A           =   db.FloatField( )
    d           =   db.FloatField( )
    ddet           =   db.FloatField( )
    bf            =   db.FloatField( )
    bfdet           =   db.FloatField( )
    tw           =   db.FloatField( )
    twdet           =   db.FloatField( )
    tf            =   db.FloatField( )
    tfdet            =   db.FloatField( )
    kdes           =   db.FloatField( )
    kdet           =   db.FloatField( )
    x           =   db.FloatField( )
    eo           =   db.FloatField( )
    xp           =   db.FloatField( )
    Ix            =   db.FloatField( )
    Zx            =   db.FloatField( )
    Sx            =   db.FloatField( )
    rx            =   db.FloatField( )
    Iy            =   db.FloatField( )
    Zy            =   db.FloatField( )
    Sy            =   db.FloatField( )
    ry            =   db.FloatField( )
    J            =   db.FloatField( )
    Cw            =   db.FloatField( )
    Wno           =   db.FloatField( )
    Sw1           =   db.FloatField( )
    Sw2           =   db.FloatField( )
    Sw3           =   db.FloatField( )
    Qf           =   db.FloatField( )
    Qw           =   db.FloatField( )
    ro           =   db.FloatField( )
    H           =   db.FloatField( )
    rts           =   db.FloatField( )
    ho           =   db.FloatField( )
    PA           =   db.FloatField( )
    PB           =   db.FloatField( )
    PC           =   db.FloatField( )
    PD           =   db.FloatField( )
    T           =   db.FloatField( )
    WGi           =   db.FloatField( )
    blt            =   db.FloatField( )
    hltw            =   db.FloatField( )
    twdetl2           =   db.FloatField( )

    meta = {'db_alias': 'calc_db', 'collection': 'aisc_sections_channel'}

class AISCSectionsWF(db.Document):
    _id         =   db.ObjectIdField()
    Type        =   db.StringField()
    EDI_Std_Nomenclature  = db.StringField()
    AISC_name   =   db.StringField()
    T_F         =   db.StringField()
    W           =   db.FloatField( )
    A           =   db.FloatField( )
    d           =   db.FloatField( )
    ddet           =   db.FloatField( )
    bf            =   db.FloatField( )
    bfdet           =   db.FloatField( )
    tw           =   db.FloatField( )
    twdet           =   db.FloatField( )
    tf            =   db.FloatField( )
    tfdet            =   db.FloatField( )
    kdes           =   db.FloatField( )
    kdet           =   db.FloatField( )
    k1           =   db.FloatField( )
    Ix            =   db.FloatField( )
    Zx            =   db.FloatField( )
    Sx            =   db.FloatField( )
    rx            =   db.FloatField( )
    Iy            =   db.FloatField( )
    Zy            =   db.FloatField( )
    Sy            =   db.FloatField( )
    ry            =   db.FloatField( )
    J            =   db.FloatField( )
    Cw            =   db.FloatField( )
    Wno           =   db.FloatField( )
    Sw1           =   db.FloatField( )
    Qf           =   db.FloatField( )
    Qw           =   db.FloatField( )
    rts           =   db.FloatField( )
    ho           =   db.FloatField( )
    PA           =   db.FloatField( )
    PB           =   db.FloatField( )
    PC           =   db.FloatField( )
    PD           =   db.FloatField( )
    T           =   db.FloatField( )
    WGi           =   db.FloatField( )
    bfl2tf            =   db.FloatField( )
    hltw            =   db.FloatField( )
    twdetl2           =   db.FloatField( )

    meta = {'db_alias': 'calc_db', 'collection': 'aisc_sections_WF'}


class AISCSectionsT(db.Document):
    _id         =   db.ObjectIdField()
    Type        =   db.StringField()
    EDI_Std_Nomenclature  = db.StringField()
    AISC_name   =   db.StringField()
    T_F         =   db.StringField()
    W           =   db.FloatField( )
    A           =   db.FloatField( )
    d           =   db.FloatField( )
    ddet           =   db.FloatField( )
    bf            =   db.FloatField( )
    bfdet           =   db.FloatField( )
    tw           =   db.FloatField( )
    twdet           =   db.FloatField( )
    tf            =   db.FloatField( )
    tfdet            =   db.FloatField( )
    kdes           =   db.FloatField( )
    kdet           =   db.FloatField( )
    y           =   db.FloatField( )
    yp           =   db.FloatField( )
    Ix            =   db.FloatField( )
    Zx            =   db.FloatField( )
    Sx            =   db.FloatField( )
    rx            =   db.FloatField( )
    Iy            =   db.FloatField( )
    Zy            =   db.FloatField( )
    Sy            =   db.FloatField( )
    ry            =   db.FloatField( )
    J            =   db.FloatField( )
    Cw            =   db.FloatField( )
    ro           =   db.FloatField( )
    H           =   db.FloatField( )
    PA           =   db.FloatField( )
    PB           =   db.FloatField( )
    PC           =   db.FloatField( )
    PD           =   db.FloatField( )
    WGi           =   db.FloatField( )
    Dlt            =   db.FloatField( )
    bfl2tf            =   db.FloatField( )
    twdetl2           =   db.FloatField( )

    meta = {'db_alias': 'calc_db', 'collection': 'aisc_sections_T'}

class AISCSectionsL(db.Document):
    _id         =   db.ObjectIdField()
    Type        =   db.StringField()
    EDI_Std_Nomenclature  = db.StringField()
    AISC_name   =   db.StringField()
    T_F         =   db.StringField()
    W           =   db.FloatField( )
    A           =   db.FloatField( )
    d           =   db.FloatField( )
    b           =   db.FloatField( )
    t           =   db.FloatField( )
    kdes           =   db.FloatField( )
    kdet           =   db.FloatField( )
    x           =   db.FloatField( )
    y           =   db.FloatField( )
    xp           =   db.FloatField( )
    yp           =   db.FloatField( )
    Ix            =   db.FloatField( )
    Zx            =   db.FloatField( )
    Sx            =   db.FloatField( )
    rx            =   db.FloatField( )
    Iy            =   db.FloatField( )
    Zy            =   db.FloatField( )
    Sy            =   db.FloatField( )
    ry            =   db.FloatField( )
    Iz           =   db.FloatField( )
    rz           =   db.FloatField( )
    Sz           =   db.FloatField( )
    J            =   db.FloatField( )
    Cw            =   db.FloatField( )
    ro           =   db.FloatField( )
    H           =   db.FloatField( )
    Iw           =   db.FloatField( )
    zA           =   db.FloatField( )
    zB           =   db.FloatField( )
    zC           =   db.FloatField( )
    wA           =   db.FloatField( )
    wB           =   db.FloatField( )
    wC           =   db.FloatField( )
    SwA           =   db.FloatField( )
    SwB           =   db.FloatField( )
    SwC           =   db.FloatField( )
    SzA           =   db.FloatField( )
    SzB           =   db.FloatField( )
    SzC           =   db.FloatField( )
    PA           =   db.FloatField( )
    PA2           =   db.FloatField( )
    PB           =   db.FloatField( )
    blt            =   db.FloatField( )
    tana            =   db.FloatField( )

    meta = {'db_alias': 'calc_db', 'collection': 'aisc_sections_L'}

class AISCSections2L(db.Document):
    _id         =   db.ObjectIdField()
    Type        =   db.StringField()
    EDI_Std_Nomenclature  = db.StringField()
    AISC_name   =   db.StringField()
    T_F         =   db.StringField()
    W           =   db.FloatField( )
    A           =   db.FloatField( )
    d           =   db.FloatField( )
    b           =   db.FloatField( )
    t           =   db.FloatField( )
    y            =   db.FloatField( )
    yp           =   db.FloatField( )
    Ix            =   db.FloatField( )
    Zx            =   db.FloatField( )
    Sx            =   db.FloatField( )
    rx            =   db.FloatField( )
    Iy            =   db.FloatField( )
    Zy            =   db.FloatField( )
    Sy            =   db.FloatField( )
    ry            =   db.FloatField( )
    ro           =   db.FloatField( )
    H           =   db.FloatField( )
    blt            =   db.FloatField( )

    meta = {'db_alias': 'calc_db', 'collection': 'aisc_sections_2L'}

class AlumShapesL(db.Document):
    _id         =   db.ObjectIdField()
    Size        =   db.StringField()
    Type        =   db.StringField()
    d           =   db.FloatField( )
    b           =   db.FloatField( )
    t           =   db.FloatField( )
    R1           =   db.FloatField( )
    R2           =   db.FloatField( )
    W            =   db.FloatField( )
    A           =   db.FloatField( )
    Ix            =   db.FloatField( )
    Sx            =   db.FloatField( )
    rx            =   db.FloatField( )
    y            =   db.FloatField( )
    Iy            =   db.FloatField( )
    Sy            =   db.FloatField( )
    ry            =   db.FloatField( )
    x            =   db.FloatField( )
    Iz            =   db.FloatField( )
    rz            =   db.FloatField( )
    a            =   db.FloatField( )

    meta = {'db_alias': 'calc_db', 'collection': 'alum_shapes_L'}

class AlumShapesChannel(db.Document):
    _id         =   db.ObjectIdField()
    Size        =   db.StringField()
    Type        =   db.StringField()
    d           =   db.FloatField( )
    b           =   db.FloatField( )
    tftip           =   db.FloatField( )
    tf           =   db.FloatField( )
    tw           =   db.FloatField( )
    R1           =   db.FloatField( )
    R2           =   db.FloatField( )
    d1           =   db.FloatField( )
    A           =   db.FloatField( )
    W            =   db.FloatField( )
    Ix            =   db.FloatField( )
    Sx            =   db.FloatField( )
    rx            =   db.FloatField( )
    Iy            =   db.FloatField( )
    Sy            =   db.FloatField( )
    ry            =   db.FloatField( )
    x            =   db.FloatField( )

    meta = {'db_alias': 'calc_db', 'collection': 'alum_shapes_channel'}

class AlumShapesCircular(db.Document):
    _id         =   db.ObjectIdField()
    Size        =   db.StringField()
    OD           =   db.FloatField( )
    ID           =   db.FloatField( )
    t           =   db.FloatField( )
    A           =   db.FloatField( )
    W            =   db.FloatField( )
    I            =   db.FloatField( )
    S            =   db.FloatField( )
    Z           =   db.FloatField( )
    r            =   db.FloatField( )
    J           =   db.FloatField( )
    Rblt           =   db.FloatField( )

    meta = {'db_alias': 'calc_db', 'collection': 'alum_shapes_circular'}

class AlumShapesRectangular(db.Document):
    _id         =   db.ObjectIdField()
    Name        =   db.StringField()
    Type        =   db.StringField()
    d           =   db.FloatField( )
    b           =   db.FloatField( )
    t           =   db.FloatField( )
    W            =   db.FloatField( )
    A           =   db.FloatField( )
    Ix            =   db.FloatField( )
    Sx            =   db.FloatField( )
    Zx            =   db.FloatField( )
    rx            =   db.FloatField( )
    Iy            =   db.FloatField( )
    Sy            =   db.FloatField( )
    Zy            =   db.FloatField( )
    ry            =   db.FloatField( )
    J            =   db.FloatField( )

    meta = {'db_alias': 'calc_db', 'collection': 'alum_shapes_rectangular'}

class AlumShapesWF(db.Document):
    _id         =   db.ObjectIdField()
    Size        =   db.StringField()
    Type        =   db.StringField()
    d           =   db.FloatField( )
    bf           =   db.FloatField( )
    tf           =   db.FloatField( )
    tw           =   db.FloatField( )
    R1           =   db.FloatField( )
    R2           =   db.FloatField( )
    d1           =   db.FloatField( )
    A           =   db.FloatField( )
    W            =   db.FloatField( )
    Ix            =   db.FloatField( )
    Sx            =   db.FloatField( )
    Zx            =   db.FloatField( )
    rx            =   db.FloatField( )
    Iy            =   db.FloatField( )
    Sy            =   db.FloatField( )
    Zy            =   db.FloatField( )
    ry            =   db.FloatField( )
    Cw            =   db.FloatField( )
    J            =   db.FloatField( )

    meta = {'db_alias': 'calc_db', 'collection': 'alum_shapes_wf'}
